name: Build and deploy code

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:
  jobs1:
    environment: # Reference the environment created at the github repo, contains the secrets for env
      name: env_build_deploy
    env: 
          DB_HOSTNAME: ${{secrets.DB_HOSTNAME}}
          DB_PORT: ${{secrets.DB_PORT}} 
          DB_NAME: ${{secrets.DB_NAME}} 
          DB_USERNAME: ${{secrets.DB_USERNAME}} 
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}        
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          ALGORITHM: ${{secrets.ALGORITHM}}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}} 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: install python version 3.10.1
        uses: actions/setup-python@v3
        with: 
          python-version: "3.10.1"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: run tests with pytest
        run: |
          pip install pytest
          pytest