name: Build and deploy code

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:
  jobs1:
    env: 
          DB_HOSTNAME: localhost
          DB_PORT: 5432
          DB_NAME: fastapi
          DB_USERNAME: postgres
          DB_PASSWORD: DevpAa3030
          SECRET_KEY: 7a57a614793070173b21c8aa51c57f6e5d4c847a4d5cc4c19d437fa34b1fab51
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: install python version 3.10.1
        uses: actions/setup-python@v3
        with: 
          python-version: "3.10.1"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: run tests with pytest
        run: |
          pip install pytest
          pytest