name: Build and deploy code

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: just a test command
        run: echo "test command run"